spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/lessons/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/users/**, /api/users
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /ws/messages/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/video
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**, /api/payments
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    healthcheck:
      enabled: true
logging:
  level:
    root: WARN
    org:
      springframework: INFO